# Generated by Django 5.1.4 on 2025-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("date_of_birth", models.DateField()),
                ("faculty", models.CharField(max_length=300)),
                ("promotion", models.CharField(max_length=100)),
                ("first_choice", models.CharField(max_length=300)),
                ("second_choice", models.CharField(max_length=300)),
            ],
        ),
    ]
